### ISSUE TITLE
How can create fix btn or anythings

### ISSUE THREAD

**Issue by hemedani** [jtrussell/angular-snap.js#100]
how can create position fixed in snap-content element 
for example make 
`<button class="..." snap-toggle="right">Toggle Right</button>` 
to fixed in
`... {
  position: fixed;
  top: 5rem;
  right: 0;
}`
in this example http://plnkr.co/edit/iB8VfD?p=preview

and when scrolling the page position of the button did not change

**Comment by jtrussell** [comment]
Are you saying you'd like an element (for example, a button) to move with your snap-content it is open/shut but to also remain fixed vertically when the page is scrolled? There's nothing within Snap.js or angular-snap.js that supports this directly. Apparently though some forks may have attempted exactly that (see this thread: https://github.com/jakiestfu/Snap.js/issues/201). If you're going to implement this independently there seems to be plenty of prior art out there as well. Good luck!

**Comment by hemedani** [comment]
how can create `elementMirror` in angular version of snap.js ???

**Comment by jtrussell** [comment]
You have a few possible options:

- Instantiate the Snap object yourself and use `snapRemote.register` to provide it to angular-snap.
- Get the automatically created Snap instance with `snapRemote.getSnapper` then update it with `snapper.settings(... new settings ...)` - I'm not sure if this will work, depends on how the `elementMirror` stuff was implemented and I haven't worked with it myself.
- Fork this repo and support that fork of Snap.js

**Comment by hemedani** [comment]
tnx man

**Comment by jtrussell** [comment]
Good luck!
