### ISSUE TITLE
snap-toggle

### ISSUE THREAD

**Issue by m-apsolon** [jtrussell/angular-snap.js#101]
I noticed something weird: 
when zooming to 110% in chrome, snap-toggle stops working properly: it does open the drawer, but won't close it.

this behavior occurs also in the plunker, not only in my project
http://plnkr.co/edit/5qbthSlEzCik1AtCpFj3?p=preview

**Comment by jtrussell** [comment]
Unfortunately this is due to a known issue in Snap.js itself:

https://github.com/jakiestfu/Snap.js/issues/223

The snapper erroneously reports itself as closed when zoomed in :frowning:.

I don't believe there's too much we can do on this end but I'm open to suggestions!
