### ISSUE TITLE
Compatibility with Angular 1.4.5

### ISSUE THREAD

**Issue by tomcully** [jtrussell/angular-snap.js#102]
Hey

I've just updated all of our apps bower dependencies and bower is listing:

├─┬ angular-snap#1.8.3
│ ├── angular#1.4.5 incompatible with ~1.2 (1.2.29-build.594+sha.b94a47b available, latest is 1.4.6-build.4236+sha.19ecdb5)
│ └── snapjs#1.9.3 (latest is 2.0.0-rc1)

Is there a version of angular-snap that is ok with later versions on angular?

Thanks!

**Comment by jtrussell** [comment]
Use version 1.8.4 :)

**Comment by tomcully** [comment]
@jtrussell Class! Thanks :+1:
