### ISSUE TITLE
SnapConstructor is not a function error

### ISSUE THREAD

**Issue by Majstore** [jtrussell/angular-snap.js#104]
When I use  snapContent directive I got error in line :
 snapRemote.register(new SnapConstructor(snapOptions), snapId);

Error message is 'SnapConstructor is not a function'

**Comment by jtrussell** [comment]
Do you have snap.js included on your page (in addition to angular-snap.js)?

**Comment by Majstore** [comment]
You are right ! Thanks ! I didn't include it, and it is said in installation guide.
My suggsestion is to provide snap.js too in bower installation of angular-snap.
