### ISSUE TITLE
Any api to drag over the content not to shift the content

### ISSUE THREAD

**Issue by niktrix** [jtrussell/angular-snap.js#106]
Any api to drag left drawer over the content not to shift the content, similar to gmail android application.

**Comment by jtrussell** [comment]
Nope, sorry. Snap.js is pretty firmly in the business of sliding content to reveal drawers underneath.

**Comment by ballenjr** [comment]
I was able to get this to work properly simply by reversing the roles of the content and drawer and provide appropriate start values.

Like So:
```
<style>
	.snap-content {
		width: 80vw;
		left: -40vw;
		background-color: transparent;
		border: none;
		overflow-y: hidden;
		color: black;
	}
	.snap-content section{
		width: 50vw;
		height: 100%;
		background: linear-gradient(to right, rgba(0, 0, 0, 0.44) 0%,rgba(0, 0, 0, 0.33) 83%,rgba(0,0,0,0) 100%);
	}
	.snap-drawer {
		width: 100vw;
	}
</style>

<snap-drawer style="display: block !important;">
  Main Content

</snap-drawer>

<snap-content ng-init="options = {hyperextensible: false, maxPosition: ($root.screen.width * .4), minPosition: 0}" snap-options="options">
	<section>
		Drawer Content
	</section>
	<div snap-dragger style="height:0;width:0;">
	</div>
</snap-content>
```

I realize that I polluted the $rootScope too. But in this case I don't care. And the overflow-y: hidden may not be needed anymore. But if you still want to scroll then you should still be able to embed another scrollable inside.
