### ISSUE TITLE
Drawer always visible

### ISSUE THREAD

**Issue by Chirpizard** [jtrussell/angular-snap.js#108]
I did see the comment in the FAQ :) My snap-content doesnt have any transparent areas for the drawer to show through, its just sitting directly on top of everything in snap-content. In fact, everything under the drawer is disable. If I hover over a link, for example, it doesnt respond.

I have angular-snap.js and snap.js files and both css files also. (wasnt sure if I needed them!) No console errors.

I have my snap-drawer <div snap-drawer> inside of a template html file used in a custom directive, but its all loaded in ABOVE the snap-content HTML element.

I checked the z-index, doesn't seem to be the issue. I tried to use the drawer and content as both elements and attributes.

And of course I have 'snap' loaded in as a dependency for my app. Do I need to do something with a controller? (learning Angular still!)

Thanks!

**Comment by Chirpizard** [comment]
I think just typing everything out here helped me to solve it! Sorry.
Thanks for the awesome module!

**Comment by mfyang** [comment]
buddy, how did you solve the problem?  that will be useful for other folks.
