### ISSUE TITLE
Snap constructor is not defined. Make sure window.Snap is defined or supply your own with SnapConstructorProvider.use(MySnap).

### ISSUE THREAD

**Issue by JemyDev** [jtrussell/angular-snap.js#110]
http://stackoverflow.com/questions/36448971/angularjs-and-angular-snap-snap-constructor-is-not-defined

Hi, I have a problem when I'm using your plugin. Can you help me ? I did a post on stackoverflow. Thank you very much !

**Comment by jtrussell** [comment]
Hi @JemyDev I added a comment to your SO post to get some more info. I'll close this issue and we can continue the conversation there.
