### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by jay8t6** [jtrussell/angular-snap.js#111]
I am having a weird problem with this plugin, when I switch the orientation on my phone, the whole screen goes blank and it happens randomly, does anyone have a fix for this? When I look at the web inspector on safari, it shows the computed height for snap content and snap drawer as 0.

**Comment by jtrussell** [comment]
Can you replicate the issue with jsbin? I've provided templates in the README:

https://github.com/jtrussell/angular-snap.js#reporting-issues

It would be super helpful too if you could verify that everything is working as expected for you with the template that just uses Snap.js (i.e. no Angular Snap).

Please do reopen with steps to reproduce.
