### ISSUE TITLE
Sometimes stops working

### ISSUE THREAD

**Issue by falconmick** [jtrussell/angular-snap.js#112]
I don't really know how to provide any extra debug info, other than that when I use the class to designate a button to open the sidebar OR if I use snapper.open('left') on my non touch enabled device it doesn't open. I've put a breakpoint in when I use javascript and have used snapper.state() and both before and after the call to open it the state is closed.

My partner on the team hasn't had this issue, but his dev environment has a touch enabled screen. Maybe it's something that turns on when a user doesn't have any touch enabled screens?

If I can help any more, just let me know and I'll do whatever it needs.

**Comment by falconmick** [comment]
Moved to https://github.com/jtrussell/angular-snap.js-bower/issues/8

**Comment by jtrussell** [comment]
Let's keep the issue here :)

**Comment by jtrussell** [comment]
Can you replicate a non-working example with jsbin? I've provided templates in the readme:

https://github.com/jtrussell/angular-snap.js#reporting-issues

It would be super helpful too if you could verify that everything *is* working as expected for you with the template that just uses Snap.js (i.e. no Angular Snap).

**Comment by dacloutier** [comment]
I'm having the same issue described above.

I will try to provide a working example with and without angular-snap this weekend.

**Comment by jtrussell** [comment]
Thanks - that would be super helpful!

**Comment by jtrussell** [comment]
Closed pending steps to reproduce.
