### ISSUE TITLE
 Angular 1.5.х support

### ISSUE THREAD

**Issue by antonlegkiy** [jtrussell/angular-snap.js#117]
Good day, if there will be support for angular 1.5.x? Now angular-snap support only 1.4.x || 1.2.x.
Thanks.

**Comment by jtrussell** [comment]
I have no reason to suspect anything will break in 1.5.x - mind submitting a PR (with updated dev deps too) and we'll see what Travis thinks of running our tests with the new version?

**Comment by antonlegkiy** [comment]
Locally works fine with angular 1.5.5. I send a PR and Travis tests pased successfully. Could you please clarify,  is it correct that I added only angular 1.5.x to the list of angular gruntfile versions? thank you in advance

**Comment by antonlegkiy** [comment]
I see comment to PR, thx

**Comment by jtrussell** [comment]
Version 1.8.6 allows angular 1.5.x - thanks for the PR :).
