### ISSUE TITLE
Dragging to close the left drawer can be initiated inside the drawer in mobile browser

### ISSUE THREAD

**Issue by sey** [jtrussell/angular-snap.js#74]
Hello, 

I don't know if this issue is more relevant for this project or for the snap project.
The problem is the following (you can test this behavior on the simulator or a real device on the demo page for example http://jtrussell.github.io/angular-snap.js/):
- on iOS, open the left drawer either by clicking on a menu button or by dragging the content to the right.
- then you can close the drawer by dragging inside the drawer which I think is a bug as you can't do this on the desktop with a mouse.
- also it produces a weird behavior where you can sometimes see white space on the right side (as if it wanted to open a right drawer). 
- if you try to re-open the left drawer you can see some flickering as if the state of the drawer were temporarily broken.

**Comment by athar21200** [comment]
Same issue, with iPhone 6, and many other. Tried different mobiles and i found same issue. It's not good. Please update it asap,

We will thankful for this act of kindness.

Regards

**Comment by jtrussell** [comment]
I'd love to put this issue to rest and I'd welcome help in solving it. What we really need to move forward is two demos (jsbin, jsfiddle, etc.):

- The first should use `Snap.js` alone (i.e. no Angular), it *should not* exhibit this issue.
- The second should use `angular-snap` and make use of the exact same features as the first example. It *should* exhibit this issue.

I haven't been able to replicate the issue myself (iPhone 6s) so I'd greatly appreciate someone who is observing the issue to build the above examples and confirm it is happening in one case but not the other.

**Comment by sey** [comment]
Quickly testing on an iPhone 6s (iOS 9) I am not able to reproduce the problem either. 
But I am still able to destroy the menu state but I think this is mainly due to the new back and forward swipe gestures of Safari. 
My feeling is that it should not be used outside of a web app wrapped in a native app to prevent the native behavior of Safari.
