### ISSUE TITLE
snap drag causing issue with ng Grid drag for Grouping functionality

### ISSUE THREAD

**Issue by madasuk** [jtrussell/angular-snap.js#83]
Hi, Is there any possibility to disable the drag feature in angular snap. Because in ng Grid, I need to drag column header for grouping functionality (This ng Grid is inside snap content)  but when I do it, snap drawer is opening in up, instead firing ng grid grouping functionality. Then onwards if I click snap toggle button in snap drawer, snap content is opening and closing instead snap drawer. And snap-drawer is never getting closed since then. If I can fully disable drag behavior in angular snap, I think this issue will be resolved. Could you please tell me how can I do it?

**Comment by jtrussell** [comment]
Closing this for now - let me know if you have other questions!
