### ISSUE TITLE
Disable all drawers in non mobile resolutions

### ISSUE THREAD

**Issue by xzegga** [jtrussell/angular-snap.js#85]
I have a responsive app with different style in mobile resolution and desktop resolution minor than 768px, how I can disable all drawers (left and right) in resolution minor to 768px?.

I have a directive for check my resolution like this:

    angular.module('msx').directive('mobileScreenSwitcher', function ($window, snapRemote) {
	    return {
	        restrict: 'E',
	        link: function (scope) {

	            $window.onresize = function () {
	                checkResolution();
	            };
	            checkResolution();

	            function checkResolution() {                
	                var screenWidth = $window.innerWidth;
	                if (screenWidth >= 768) {	              
	                    // I want disable all drawers in this line.
	                    snapRemote.globalOptions.disable = 'left';
	                }
	            }
	        }
	    }
    });

**Comment by jtrussell** [comment]
Take a look at #50.

**Comment by Luddinus** [comment]
+1...
