### ISSUE TITLE
Add an NPM module

### ISSUE THREAD

**Issue by lee-40square** [jtrussell/angular-snap.js#87]
Would be nice to be able to install as an NPM module.

**Comment by jtrussell** [comment]
Sure thing. I don't use npm to manage front end deps - are there any fields you'd need other than the usual in the package.json file? I.e. is it conventional to list the main files as in bower.json?

**Comment by jtrussell** [comment]
It's up under `angular-snap` as of v1.8.1. Snap.js itself isn't on npm and I don't much like the idea of tracking down shasums to match version numbers over there so I'm leaving it off the dependency list for now. If you can convince @jakiestfu to publish on npm or have a tidy solution for syncing up versions I'd be more than happy to list it as a dependency too.

**Comment by lee-40square** [comment]
Thanks @jtrussell. Appreciate it.
