### ISSUE TITLE
error while running on Internet Explorer 9 (IE9)

### ISSUE THREAD

**Issue by smart987** [jtrussell/angular-snap.js#88]
Hi jtrussell, Thanks for the nice plugin. However it is not working on IE9. I am getting the following error when I try to run in IE9. Any solution please ...

"Unable to get property 'match' of undefined or null reference".

I am getting this error near the following code snippet in snap.js

else {
                            var matrix = win.getComputedStyle(settings.element)[cache.vendor+'Transform'].match(/\((.*)\)/),
                                ieOffset = 8;
....

**Comment by smart987** [comment]
![GitHub Logo](Desktop/angularSnap-ie9Error.png)

**Comment by jtrussell** [comment]
The issue resides with [Snap.js](https://github.com/jakiestfu/Snap.js) itself, the underlying library that angular-snap provides a wrapper for. There's already an issue open over there for exactly this problem too in case you want to chime in:

https://github.com/jakiestfu/Snap.js/issues/89

Looks like there are also some open pull requests that might address the problem.
