### ISSUE TITLE
how can I limit the size of the drawer?

### ISSUE THREAD

**Issue by bleekbless** [jtrussell/angular-snap.js#90]
I want to set a limit size for the sidebar drawer, how can I do that ?

**Comment by jtrussell** [comment]
You'll want to set the [`minPosition` and `maxPosition` settings](https://github.com/jakiestfu/Snap.js#settings-and-defaults) and also override the width assigned to the `.snap-drawer` class (defaults to 265px).

**Comment by bleekbless** [comment]
thanks you
