### ISSUE TITLE
Open/Close issue

### ISSUE THREAD

**Issue by bleekbless** [jtrussell/angular-snap.js#91]
how can I do something when I swipe to open or swipe to close de drawer? Like when I open the drawer by swipe right show some message;.

**Comment by jtrussell** [comment]
You can use [`snapper.on`](https://github.com/jakiestfu/Snap.js#on-adds-an-event-hook) to register event handlers with specific snapper instances. Is that what you're looking for?

**Comment by bleekbless** [comment]
Hey, this is exactly what I was looking, but the method 'open' doesnt work
:C

2015-06-08 17:15 GMT-03:00 Justin Russell <notifications@github.com>:

**Comment by jtrussell** [comment]
Would you mind creating a demo with [one of these] to show me what you mean?

**Comment by bleekbless** [comment]
http://jsbin.com/cawevumiha/1/watch?html,css,js,output

2015-06-09 12:54 GMT-03:00 Justin Russell <notifications@github.com>:

**Comment by jtrussell** [comment]
You probably want to be using the [snap remote service](https://github.com/jtrussell/angular-snap.js#snapremote) to get a reference to the snapper object being used, in most cases you should never need to say `new Snap(...)` yourself.

http://jsbin.com/kujohuxeha/1/edit?html,js,output

**Comment by bleekbless** [comment]
Oh yes,  thank you!!
Em 10/06/2015 08:49, "Justin Russell" <notifications@github.com> escreveu:
