### ISSUE TITLE
snap-drawer content always shows

### ISSUE THREAD

**Issue by SteveEmmerich** [jtrussell/angular-snap.js#93]
Hi,

i have a snap-drawer setup and a snap-content under it, everything appears to match the examples. However all of my content for the snap-drawer always shows. it never goes away, whether the drawer is open or closed. I have reduced the html inside of it to just text. Do you have an ideas?

**Comment by jtrussell** [comment]
Does your snap-content have a background color? This component doesn't apply one automatically.

**Comment by SteveEmmerich** [comment]
No no back ground in either the snap-content or the drawer. I started with
just text first to see if it worked. does it need a background color?

On Fri, Jun 26, 2015 at 2:21 AM, Justin Russell <notifications@github.com>
wrote:

> Does your snap-content have a background color? This component doesn't
> apply one automatically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jtrussell/angular-snap.js/issues/93#issuecomment-115572327>
> .
>



-- 
Thank you for your time,
-Steve Emmerich

**Comment by jtrussell** [comment]
You'll usually want some sort background on the content at least. Check out the first item in the FAQ: https://github.com/jtrussell/angular-snap.js/blob/master/README.md#faq

**Comment by jtrussell** [comment]
Closing this (assuming the above resolved your issue). Feel free to reopen if needed.
