### ISSUE TITLE
Possible to have multi layered drawers?

### ISSUE THREAD

**Issue by amritk** [jtrussell/angular-snap.js#96]
Is it possible to pull out a left drawer, then pull out another left drawer on top of it?

**Comment by jtrussell** [comment]
I'm not 100% sure what you mean by "on top of it", the drawers are opened by essentially sliding divs around to reveal hidden content. In theory though you can have as many `snap-content`s as you like in your app in whatever configuration you like. Were you running into issues?

**Comment by amritk** [comment]
So I tried throwing in a snap-content inside the left snap-drawer. It slides around controllably. Would there be a way that I could set bounds on it? Like it starts off screen and cannot be dragged beyond x pixels.

Here is what I am trying to do, from an article on [codrops](http://tympanus.net/Development/MultiLevelPushMenu/):

Start with a regular left drawer that you pull out:

![screen shot 2015-07-06 at 12 37 34 pm](https://cloud.githubusercontent.com/assets/2039539/8531485/902a3c72-23dc-11e5-8a21-096e1fda54b4.png)
![screen shot 2015-07-06 at 12 37 21 pm](https://cloud.githubusercontent.com/assets/2039539/8531487/93f08eb0-23dc-11e5-89a0-7a8be531ab28.png)

Then pull another drawer out over top of this one, that doesn't quite cover it:

![screen shot 2015-07-06 at 12 37 46 pm](https://cloud.githubusercontent.com/assets/2039539/8531497/a5b3bc26-23dc-11e5-916e-f17566d0b33f.png)

**Comment by jtrussell** [comment]
I see. I think it would be tough to accomplish exactly that with this module. You can see an example with nested drawers [here](https://github.com/jtrussell/angular-snap.js/blob/master/examples/partials/ex-two-snappers.html) - or by running `grunt examples` and checking out the two snappers example. Someone over on the Snap.js proper repo might have more ideas for you too.

**Comment by amritk** [comment]
Yea its not quite what I was looking for, thanks anyway. I'll check out Snap.js and see if I can get it going.
