### ISSUE TITLE
bower.json should contain license information

### ISSUE THREAD

**Issue by stanleyxu2005** [jtrussell/angular-snap.js#97]
In order to include javascript libraries for java application, I usually use webjar, which is a package management system for java/scala. I tried to submit angular-snap 1.8.2 http://www.webjars.org/bower, but failed. The reason is bower.json does not contain a license information. Could you please add a field license:"MIT" in bower.json.

**Comment by jtrussell** [comment]
Thanks, should be available in 1.8.3+.
