### ISSUE TITLE
Snap-drawer show when page loads

### ISSUE THREAD

**Issue by bleekbless** [jtrussell/angular-snap.js#98]
I'm building an app with PhoneGap and I am using Angular-Snap and when the app loads the Snap-drawer always shows first, I want to the Snap-Content to be seen first

**Comment by jtrussell** [comment]
Is your code somewhere I can see? How are you including the angular snap (and snap.js if necessary) styles in your app?

**Comment by bleekbless** [comment]
yes I commit it to github, here [lookbook](https://github.com/bleekbless/lookbook) I tried to set the snap-Content z-index to 9000 but snap drawer still showing first

**Comment by jtrussell** [comment]
You had a handful of modifications to the angular-snap styles - it seemed like things worked as expected for me when I replaced the stylesheets/scripts in your repo with the most recent build (without modification). Would you mind trying with the most recent version?
